const paramsActionTypes = {
	PARAMS_ASSETS_SET_DATA: 'PARAMS_ASSETS_SET_DATA',
	PARAMS_SAFEGUARDS_SET_DATA: 'PARAMS_SAFEGUARDS_SET_DATA',
	SET_PROJECT_NAME: 'SET_PROJECT_NAME',
}

export default paramsActionTypes
