const projectActionTypes = {
	PROJECTS_GET_DATA: 'PROJECTS_GET_DATA',
	ASSETS_GET_DATA: 'ASSETS_GET_DATA',
	SAFEGUARDS_GET_DATA: 'SAFEGUARDS_GET_DATA',
	PROJECT_SET_ASSETS_DEPENDENCIES: 'PROJECT_SET_ASSETS_DEPENDENCIES',
	PROJECT_SET_ASSETS_NEW_DEPENDENCIES: 'PROJECT_SET_ASSETS_NEW_DEPENDENCIES',
	PROJECT_SET_ASSETS_DEPENDENCY_ID: 'PROJECT_SET_ASSETS_DEPENDENCY_ID',
	PROJECT_SET_ASSETS_CLASS_CATALOG: 'PROJECT_SET_ASSETS_CLASS_CATALOG',
	PROJECT_SET_ASSETS_VALUATION_CATALOG: 'PROJECT_SET_ASSETS_VALUATION_CATALOG',
	PROJECT_SET_THREAT_CATALOG: 'PROJECT_SET_THREAT_CATALOG',
	PROJECT_SET_SAFEGUARDS_CATALOG: 'PROJECT_SET_SAFEGUARDS_CATALOG',
}

export default projectActionTypes
