const projectActionTypes = {
	PROJECTS_GET_DATA: 'PROJECTS_GET_DATA',
	ASSETS_GET_DATA: 'ASSETS_GET_DATA',
	PROJECT_SET_ASSETS_DEPENDENCIES: 'PROJECT_SET_ASSETS_DEPENDENCIES',
	PROJECT_SET_ASSETS_NEW_DEPENDENCIES: 'PROJECT_SET_ASSETS_NEW_DEPENDENCIES',
	PROJECT_SET_ASSETS_DEPENDENCY_ID: 'PROJECT_SET_ASSETS_DEPENDENCY_ID',
}

export default projectActionTypes
