const projectFormActionTypes = {
	PROJECTS_FORM_TOGGLE: 'PROJECTS_FORM_TOGGLE',
	PROJECTS_SET_FORM_DATA: 'PROJECTS_SET_FORM_DATA',
	ASSETS_FORM_TOGGLE: 'ASSETS_FORM_TOGGLE',
	ASSETS_SET_FORM_DATA: 'ASSETS_SET_FORM_DATA',
	SAFEGUARDS_FORM_TOGGLE: 'SAFEGUARDS_FORM_TOGGLE',
	SAFEGUARDS_FORM_CHILDREN_TOGGLE: 'SAFEGUARDS_FORM_CHILDREN_TOGGLE',
	SAFEGUARDS_SET_FORM_DATA: 'SAFEGUARDS_SET_FORM_DATA',
	UPLOAD_TOGGLE: 'UPLOAD_TOGGLE',
}

export default projectFormActionTypes
