const projectFormActionTypes = {
	PROJECTS_FORM_TOGGLE: 'PROJECTS_FORM_TOGGLE',
	PROJECTS_SET_FORM_DATA: 'PROJECTS_SET_FORM_DATA',
	ASSETS_FORM_TOGGLE: 'ASSETS_FORM_TOGGLE',
	ASSETS_SET_FORM_DATA: 'ASSETS_SET_FORM_DATA',
}

export default projectFormActionTypes
