export const paths = {
	ROOT_APP: '/',
	LOGIN: '/login',
	REGISTER: '/registro',
	FORGOT_PASSWORD: '/olvido-contrasena',
	RESET_PASSWORD: '/restablecer-contrasena',
	SAFEGUARDS: '/salvaguardas',
	SAFEGUARDS_IDENTIFICATION: '/salvaguardas/identificacion',
	SAFEGUARDS_VALUATION: '/salvaguardas/valoracion',
	THREATS: '/amenazas',
	THREAT_IDENTIFICATION: '/amenazas/identificacion',
	THREAT_VALUATION: '/amenazas/valoracion',
	ASSETS: '/activos',
	ASSETS_IDENTIFICATION: '/activos/identificacion',
	ASSETS_VALUATION: '/activos/valoracion',
	ASSETS_REGISTER: '/activos/dependencias',
	ASSETS_LIST: '/activos/lista',
	STATICS: '/estadisticas',
	PROJECTS: '/proyectos',
	SAFEGUARDS_VALUATION_THREATS: '/salvaguardas-amenazas/valoracion',
	STATE: '/estado-riesgo',
	STATE_POTENTIAL_IMPACT: '/estado-riesgo/impacto-potencial',
	STATE_RESIDUAL_IMPACT: '/estado-riesgo/impacto-residual',
	STATE_POTENTIAL_RISK: '/estado-riesgo/riesgo-potencial',
	STATE_RESIDUAL_RISK: '/estado-riesgo/riesgo-residual',
}
